---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: openai-secret
  namespace: default
spec:
  encryptedData:
    OPENAI_API_KEY: AgBDmD00X+YpTj3ltVrM0Bcn2BqE9fnOTsqgREekQ84JzvNiy3t1oc99NDqikoC/Ezcj3lrH7+galgeV1jC+pFJeu4fGBBSv4pry5Ys47xzhDBJZtsTsejRCn5AsC8GNt0/D5BrwG4SeplgeBLehJYhpuUcQDs8YhSJ+fz7aW6qNMm8yaZmNLJtO9gA+Yemx2q/Rza26Z/64ymPvHV1bj5095fv5QY+F3WgpG0w4cMy1WspavcCSCQbOkZlg8dCMUpLeKIIv6j5pPYhK5Bs32VEGbxh+9ncRQV3rR18lX7uwyWAsYY9EZAESnPhV4NoWrxVm70DdfX4ULY0fKWdgi53DHQ7TCsZioYrCMFc3ewKxZx7DToYffe34CV7UJqHLuI5Jqj6GrJ/HgNuLuPHPDieWor1c62eGmQMFcEFqWWqeP0aZ24aSknn53iJBFQHNIvBoSSMnkGLt+WowccUuF3MC4RNnsO+d+B7zZdiRWgJRWzbgQGVrT3zYuzn/pema8BUYoJXW6Rj+XqqFf7ff/WIZyQulgSuG6ObUelRTO6J9l8v9ra4Hf41DQeN37FUAUugnAMl250pGcD020OH5xrlCw6IMNyYqVF4oZsHOW4S1OEHUpD6i8F5vkg/zTi0jFMhMQ0VknL0vKTC9+eQsOYe9iNBYIeIlBn+Cq0fNhOv8lvADcE6YMmGOkLIcfQgt564g71qUh1gB/0hoxB+5XzRVnPaaR8ZyP0BkSr7Km3RP2EQkmhEqGlX0QncJiqvi1qNCyCwQnz8v4+xZT9lbDg4ixqciLkfQGcLjvPSpavmTRD6Mdqm7YTvle2GoEi8F+J6h2XcB5WobLu6Q7qs2DtzLtahD5s8Nw3bBE9vkWK8PFqBNIIbbDTAVyoR8Su8LV64wJjSHBRstJqXddvvFTNBGZQv+Bg==
  template:
    metadata:
      creationTimestamp: null
      name: openai-secret
      namespace: default
